"""The checksum-validated layer, measured per EU country and per script.

THE CLAIM BEING TESTED, not assumed: IBAN, card and e-mail detection is
language-independent, so the twenty-four-language problem is the NAME layer's
problem and not this layer's. That was asserted in `docs/limits.md`; here it
is measured, per member state and in four scripts.

AND THE CLAIM NOT BEING MADE: this layer is not clean. A leak class reported
by independent verification reproduces at this tip, in any language, and it is
pinned below rather than being left for somebody to rediscover. A measurement
of one layer must not be read as a certificate for the other.
"""

from __future__ import annotations

import re

import pytest

from privacy_shield.identifiers import (
    IBAN_LENGTHS,
    find_cards,
    find_emails,
    find_ibans,
    iban_ok,
)
from privacy_shield.scanner import is_safe_for_external_llm

#: The 27 member states. Written out because "the EU" is not a constant
#: anywhere in this package and a list nobody can read is a list nobody
#: checks.
EU_COUNTRIES = {
    "AT": "Austria", "BE": "Belgium", "BG": "Bulgaria", "HR": "Croatia",
    "CY": "Cyprus", "CZ": "Czechia", "DK": "Denmark", "EE": "Estonia",
    "FI": "Finland", "FR": "France", "DE": "Germany", "GR": "Greece",
    "HU": "Hungary", "IE": "Ireland", "IT": "Italy", "LV": "Latvia",
    "LT": "Lithuania", "LU": "Luxembourg", "MT": "Malta",
    "NL": "Netherlands", "PL": "Poland", "PT": "Portugal", "RO": "Romania",
    "SK": "Slovakia", "SI": "Slovenia", "ES": "Spain", "SE": "Sweden",
}


#: The IBANs are generated by `schwifty` (MIT), not by arithmetic written
#: here. The first version of this file built them itself - country code, a
#: body of "1"s, mod-97 check digits - and schwifty rejects SEVEN of those 27
#: as structurally invalid: Bulgaria, Ireland, Italy, Latvia, Malta, the
#: Netherlands and Romania require alphabetic bank codes at fixed positions, so
#: a body of digits passes mod-97 and is still not an IBAN. The test passed
#: because our detector is length-and-checksum only - the same blind spot in
#: the checker and in the checked, for the seventh time in this programme.
#:
#: schwifty is an oracle nobody here wrote, which is the whole reason to use
#: it. Without it installed this file's per-country tests SKIP, loudly, rather
#: than falling back to our own arithmetic and reporting a green.
try:  # pragma: no cover - the import is the point of the skip
    import schwifty as _schwifty
except ImportError:  # pragma: no cover
    _schwifty = None

requires_schwifty = pytest.mark.skipif(
    _schwifty is None,
    reason=(
        "schwifty is not installed, so the per-country IBANs would have to be "
        "generated by this package's own arithmetic - which is the blindness "
        "this test exists to avoid. Install the [dev] extra."
    ),
)


def _iban_for(country: str) -> str:
    return str(_schwifty.IBAN.random(country_code=country))


def _assert_iban_fully_covered(sentence, iban):
    """Exactly one span, starting at the IBAN and covering it whole.

    Not `== [iban]`: a letter-bearing BBAN can coincidentally validate a
    window that overruns into the next word (see the pinned forward-overclaim
    tests below), and the union rule in `_claim` keeps that window rather
    than truncating it. What must still hold, and what a missed IBAN, a
    truncated one, a shifted start, a short end or a split into two spans
    would all violate: one span, starting exactly on the IBAN, whose `(start,
    end)` covers exactly `value` (checked against the alphanumerics of
    `sentence[start:end]`, since `value` is the run compacted of whitespace),
    and whose value is the IBAN plus at most a prefix of the word immediately
    following it.
    """
    spans = find_ibans(sentence)
    assert len(spans) == 1, (sentence, spans)
    start, end, value = spans[0]
    assert start == sentence.index(iban), (sentence, spans)
    compacted = "".join(ch for ch in sentence[start:end] if ch.isalnum())
    assert compacted == value, (sentence, spans)
    assert value.startswith(iban), (sentence, spans)
    overclaim = value[len(iban):]
    following = sentence[start + len(iban):].lstrip()
    next_word = re.match(r"\w*", following).group(0)
    assert next_word.startswith(overclaim), (sentence, spans, next_word)


@pytest.mark.parametrize("country", sorted(EU_COUNTRIES))
def test_every_eu_country_has_a_registered_iban_length(country):
    assert country in IBAN_LENGTHS, EU_COUNTRIES[country]


@requires_schwifty
@pytest.mark.parametrize("country", sorted(EU_COUNTRIES))
def test_an_iban_from_every_eu_country_is_found_inside_prose(country):
    """Five schwifty-generated IBANs per member state, in three languages.

    Five rather than one because the generator is random: a single example can
    miss a structural form the detector mishandles, and the point of borrowing
    the oracle is to stop choosing the examples ourselves.

    Asserts coverage, not exact equality: a letter-bearing BBAN (here mostly
    MT, IE, BG, RO, LV - rates and mechanism in `docs/limits.md`) can
    coincidentally validate a window that runs into the next word, kept by
    the union rule and pinned exactly below. Equality would make this test
    intermittently fail on real IBANs, in these three short sentences at a
    per-IBAN rate of roughly 0.5% (BG) down to 0.01% (LV), without catching
    anything an untruncated, single, correctly anchored span would not also
    catch.
    """
    for _ in range(5):
        iban = _iban_for(country)
        assert iban_ok(iban), (country, iban)
        for sentence in (
            f"Zahlung an {iban} bitte.",
            f"Payment to {iban} please.",
            f"Maksu tilille {iban} kiitos.",
        ):
            _assert_iban_fully_covered(sentence, iban)


@requires_schwifty
def test_our_own_iban_arithmetic_was_wrong_and_this_is_how_we_know():
    """The record of the blind spot, kept as a test rather than as a comment.

    A country code, a body of "1"s and correct mod-97 check digits is what
    this file used to test with. It is a valid IBAN by our detector's
    definition - registered length, checksum - and it is not an IBAN, in seven
    member states, because their BBAN structure requires letters where the
    digits are. Our detector accepting it is deliberate and fail-closed; a
    TEST built on it was measuring our definition against itself.
    """
    def home_made(country):
        length = IBAN_LENGTHS[country]
        body = "1" * (length - 4)
        numeric = "".join(
            str(ord(char) - 55) if char.isalpha() else char
            for char in body + country + "00"
        )
        return f"{country}{98 - int(numeric) % 97:02d}{body}"

    rejected = []
    for country in sorted(EU_COUNTRIES):
        candidate = home_made(country)
        assert iban_ok(candidate), country
        try:
            _schwifty.IBAN(candidate)
        except Exception:
            rejected.append(country)
    assert rejected == ["BG", "IE", "IT", "LV", "MT", "NL", "RO"], rejected


#: Real reproductions of the forward overclaim: somewhere inside a
#: letter-bearing BBAN (the pinned LV shape starts at offset 8, in the
#: account part, not at the bank code), a window happens to read as a
#: registered country header, so the coincidental window's mod-97 check
#: passes and `_claim`'s union rule extends the span into the following
#: word. Each was confirmed against `iban_ok` and `schwifty.IBAN` before
#: being pinned.
FORWARD_OVERCLAIM_SHAPES = [
    ("MT51QSHU044290KHHZAXXRG8DMSH9AL", "Zahlung an {iban} bitte.",
     "MT51QSHU044290KHHZAXXRG8DMSH9ALbit"),
    ("MT72HNRE31749MZRMGD53UZINWQU9M4", "Payment to {iban} please.",
     "MT72HNRE31749MZRMGD53UZINWQU9M4pl"),
    ("IE73UNCR56051804308862", "Payment to {iban} please.",
     "IE73UNCR56051804308862please"),
    ("BG56INGB879070RF5AYZFF", "Maksu tilille {iban} kiitos.",
     "BG56INGB879070RF5AYZFFkiitos"),
    ("LV92HANDFK95IOFRNXV8B", "Zahlung an {iban} bitte.",
     "LV92HANDFK95IOFRNXV8Bbitte"),
    ("RO10INGB86ERZ4M64QWHWSYJ", "Payment to {iban} please.",
     "RO10INGB86ERZ4M64QWHWSYJplea"),
]


@requires_schwifty
@pytest.mark.parametrize("iban, template, claimed", FORWARD_OVERCLAIM_SHAPES)
def test_the_forward_overclaim_is_pinned_not_fixed(iban, template, claimed):
    """A kept behaviour, not a bug: the union rule extends each of these real
    IBANs' spans into the next word's opening letters, exactly this far."""
    assert iban_ok(iban)
    assert _schwifty.IBAN(iban)
    sentence = template.format(iban=iban)
    assert [value for _s, _e, value in find_ibans(sentence)] == [claimed]


@pytest.mark.parametrize("iban, _template, _claimed", FORWARD_OVERCLAIM_SHAPES)
def test_the_same_ibans_are_claimed_exactly_without_a_following_word(
    iban, _template, _claimed
):
    """The overclaim needs an alphanumeric word right after the IBAN: alone,
    or followed only by a sentence terminator, each is claimed exactly."""
    assert [value for _s, _e, value in find_ibans(iban)] == [iban]
    assert [value for _s, _e, value in find_ibans(f"{iban}.")] == [iban]


@requires_schwifty
def test_the_forward_overclaim_can_run_past_the_first_word():
    """Pins that the over-claim is bounded by the coincidental window's own
    registered length, not by the next word: a real French IBAN whose
    over-claim runs 24 characters into three following words.

    Reproduced from `docs/limits.md`'s measurement, confirmed against
    `iban_ok` and `schwifty.IBAN` before being pinned.
    """
    iban = "FR881990680631JNRBWNCBXML39"
    assert iban_ok(iban)
    assert _schwifty.IBAN(iban)
    sentence = f"Payment to {iban} please transfer immediately tomorrow morning."
    claimed = "FR881990680631JNRBWNCBXML39pleasetransferimmediatel"
    assert [value for _s, _e, value in find_ibans(sentence)] == [claimed]


#: Real reproductions of the backward overclaim: a header-shaped token right
#: before the IBAN (here `GB82`) forms, with the IBAN's own opening
#: characters, a window that coincidentally passes mod-97 - the same union
#: rule pulling the claimed span's start backward instead of forward. Not a
#: letter-bearing-BBAN mechanism: DE and AT/FI-shaped BBANs are all digits,
#: so this reproduces for any country. Each was confirmed against `iban_ok`
#: and `schwifty.IBAN` before being pinned.
BACKWARD_OVERCLAIM_SHAPES = [
    ("MT85DNRE69277BVRIACJUA2IFSWT6HJ", "GB82MT85DNRE69277BVRIACJUA2IFSWT6HJ"),
    ("DE36711600009423455025", "GB82DE36711600009423455025"),
]


@requires_schwifty
@pytest.mark.parametrize("iban, claimed", BACKWARD_OVERCLAIM_SHAPES)
def test_the_overclaim_can_run_backward_from_a_preceding_header_shaped_token(
    iban, claimed
):
    """Pins that the union rule extends a span backward, not only forward,
    for any country: found by looping `schwifty.IBAN.random(...)` against
    `Code GB82 {iban} ok.` (MT: 150 draws to the first hit; DE: 160),
    confirmed against `iban_ok` and `schwifty.IBAN` before being pinned."""
    assert iban_ok(iban)
    assert _schwifty.IBAN(iban)
    sentence = f"Code GB82 {iban} ok."
    spans = find_ibans(sentence)
    assert [value for _s, _e, value in spans] == [claimed]
    start, end, _value = spans[0]
    idx = sentence.index(iban)
    assert start < idx
    assert start <= idx and idx + len(iban) <= end


@pytest.mark.parametrize(
    "script, sentence",
    [
        ("greek", "Πληρωμή στον λογαριασμό %s παρακαλώ."),
        ("cyrillic", "Плащане по сметка %s моля."),
        ("latin-diacritic", "Maksu tilille %s kiitos, Müller & Kovács."),
        ("maltese", "Ħlas fil-kont %s jekk jogħġbok."),
        ("mixed", "Rechnung / invoice / λογαριασμός: %s"),
    ],
)
@requires_schwifty
def test_the_validated_layer_does_not_care_what_script_surrounds_it(
    script, sentence
):
    """An IBAN, a card and an e-mail are found in Greek, Cyrillic and Maltese
    prose exactly as in German.

    This is the half of the multilingual problem that is already solved: the
    identifier's characters are digits and Latin letters in any width or
    script, the checksum is arithmetic, and the surrounding language
    contributes nothing. The name layer is where the twenty-four
    languages actually are.
    """
    iban = _iban_for("DE")
    assert [v for _s, _e, v in find_ibans(sentence % iban)] == [iban], script
    card = "4111111111111111"
    assert [v for _s, _e, v in find_cards(sentence % card)] == [card], script
    email = "vorname.nachname@example.eu"
    assert [v for _s, _e, v in find_emails(sentence % email)] == [email], script


def test_a_non_ascii_digit_account_number_is_found_in_every_language():
    """Written as a pin on a known gap - "the validated layer is
    language-independent" was only true for languages written with ASCII
    digits - and kept, under its new name, as the guarantee that closed it."""
    for card in ("٤١١١١١١١١١١١١١١١", "４１１１１１１１１１１１１１１１"):
        sentence = f"Payment {card} please."
        start = sentence.index(card)
        assert [(s, e) for s, e, _v in find_cards(sentence)] == [
            (start, start + len(card))
        ], card


# ---------------------------------------------------------------------------
# The class this measurement must NOT be read as clearing - now closed
# ---------------------------------------------------------------------------

#: A word character glued to the front of a grouped card number AND a line
#: break inside it. Each half was handled and the intersection was not: this
#: shape cleared the egress gate with "No PII detected" and the whole card
#: left the machine.
PREVIOUSLY_LEAKING_SHAPE = "Ref4111 1111\n1111 1111"


def test_the_glued_and_wrapped_card_is_caught_now():
    """This test was written as a PIN ON A LEAK and is now an assertion that
    the leak is closed.

    It was reported by independent verification, reproduced at the previous
    tip, and pinned green-while-leaking so that a fix would fail loudly. Main's
    identifier repair is that fix, and this is the loud failure being
    converted into a guarantee rather than deleted - the shape stays in the
    suite under its own name, because the class has been rediscovered in this
    programme more than once.
    """
    safe, _reason, categories = is_safe_for_external_llm(PREVIOUSLY_LEAKING_SHAPE)
    assert safe is False, "the glued-and-wrapped card leaks again"
    assert "credit_card" in categories, categories
    assert [value for _s, _e, value in find_cards(PREVIOUSLY_LEAKING_SHAPE)] == [
        "4111111111111111"
    ]


@pytest.mark.parametrize(
    "language, template",
    [
        ("de", "Rechnung %s Ende"),
        ("el", "Λογαριασμός %s τέλος"),
        ("bg", "Сметка %s край"),
        ("fi", "Lasku %s loppu"),
        ("hu", "Számla %s vége"),
        ("mt", "Kont %s tmiem"),
    ],
)
def test_the_closed_leak_is_closed_in_every_language(language, template):
    """The class was arithmetic and layout, so the fix has to hold in every
    language too - and the per-language name measurement says nothing about
    it either way, which is why this file carries both."""
    safe, _reason, categories = is_safe_for_external_llm(
        template % PREVIOUSLY_LEAKING_SHAPE
    )
    assert safe is False, language
    assert "credit_card" in categories, (language, categories)
