"""The checksum-validated layer, measured per EU country and per script.

THE CLAIM BEING TESTED, not assumed: IBAN, card and e-mail detection is
language-independent, so the twenty-four-language problem is the NAME layer's
problem and not this layer's. That was asserted in `docs/limits.md`; here it
is measured, per member state and in four scripts.

AND THE CLAIM NOT BEING MADE: this layer is not clean. A leak class reported
by independent verification reproduces at this tip, in any language, and it is
pinned below rather than being left for somebody to rediscover. A measurement
of one layer must not be read as a certificate for the other.
"""

from __future__ import annotations

import pytest

from privacy_shield.identifiers import (
    IBAN_LENGTHS,
    find_cards,
    find_emails,
    find_ibans,
    iban_ok,
)
from privacy_shield.scanner import is_safe_for_external_llm

#: The 27 member states. Written out because "the EU" is not a constant
#: anywhere in this package and a list nobody can read is a list nobody
#: checks.
EU_COUNTRIES = {
    "AT": "Austria", "BE": "Belgium", "BG": "Bulgaria", "HR": "Croatia",
    "CY": "Cyprus", "CZ": "Czechia", "DK": "Denmark", "EE": "Estonia",
    "FI": "Finland", "FR": "France", "DE": "Germany", "GR": "Greece",
    "HU": "Hungary", "IE": "Ireland", "IT": "Italy", "LV": "Latvia",
    "LT": "Lithuania", "LU": "Luxembourg", "MT": "Malta",
    "NL": "Netherlands", "PL": "Poland", "PT": "Portugal", "RO": "Romania",
    "SK": "Slovakia", "SI": "Slovenia", "ES": "Spain", "SE": "Sweden",
}


#: The IBANs are generated by `schwifty` (MIT), not by arithmetic written
#: here. The first version of this file built them itself - country code, a
#: body of "1"s, mod-97 check digits - and schwifty rejects SEVEN of those 27
#: as structurally invalid: Bulgaria, Ireland, Italy, Latvia, Malta, the
#: Netherlands and Romania require alphabetic bank codes at fixed positions, so
#: a body of digits passes mod-97 and is still not an IBAN. The test passed
#: because our detector is length-and-checksum only - the same blind spot in
#: the checker and in the checked, for the seventh time in this programme.
#:
#: schwifty is an oracle nobody here wrote, which is the whole reason to use
#: it. Without it installed this file's per-country tests SKIP, loudly, rather
#: than falling back to our own arithmetic and reporting a green.
try:  # pragma: no cover - the import is the point of the skip
    import schwifty as _schwifty
except ImportError:  # pragma: no cover
    _schwifty = None

requires_schwifty = pytest.mark.skipif(
    _schwifty is None,
    reason=(
        "schwifty is not installed, so the per-country IBANs would have to be "
        "generated by this package's own arithmetic - which is the blindness "
        "this test exists to avoid. Install the [dev] extra."
    ),
)


def _iban_for(country: str) -> str:
    return str(_schwifty.IBAN.random(country_code=country))


@pytest.mark.parametrize("country", sorted(EU_COUNTRIES))
def test_every_eu_country_has_a_registered_iban_length(country):
    assert country in IBAN_LENGTHS, EU_COUNTRIES[country]


@requires_schwifty
@pytest.mark.parametrize("country", sorted(EU_COUNTRIES))
def test_an_iban_from_every_eu_country_is_found_inside_prose(country):
    """Five schwifty-generated IBANs per member state, in three languages.

    Five rather than one because the generator is random: a single example can
    miss a structural form the detector mishandles, and the point of borrowing
    the oracle is to stop choosing the examples ourselves.
    """
    for _ in range(5):
        iban = _iban_for(country)
        assert iban_ok(iban), (country, iban)
        for sentence in (
            f"Zahlung an {iban} bitte.",
            f"Payment to {iban} please.",
            f"Maksu tilille {iban} kiitos.",
        ):
            assert [value for _s, _e, value in find_ibans(sentence)] == [iban], (
                country,
                sentence,
            )


@requires_schwifty
def test_our_own_iban_arithmetic_was_wrong_and_this_is_how_we_know():
    """The record of the blind spot, kept as a test rather than as a comment.

    A country code, a body of "1"s and correct mod-97 check digits is what
    this file used to test with. It is a valid IBAN by our detector's
    definition - registered length, checksum - and it is not an IBAN, in seven
    member states, because their BBAN structure requires letters where the
    digits are. Our detector accepting it is deliberate and fail-closed; a
    TEST built on it was measuring our definition against itself.
    """
    def home_made(country):
        length = IBAN_LENGTHS[country]
        body = "1" * (length - 4)
        numeric = "".join(
            str(ord(char) - 55) if char.isalpha() else char
            for char in body + country + "00"
        )
        return f"{country}{98 - int(numeric) % 97:02d}{body}"

    rejected = []
    for country in sorted(EU_COUNTRIES):
        candidate = home_made(country)
        assert iban_ok(candidate), country
        try:
            _schwifty.IBAN(candidate)
        except Exception:
            rejected.append(country)
    assert rejected == ["BG", "IE", "IT", "LV", "MT", "NL", "RO"], rejected


@pytest.mark.parametrize(
    "script, sentence",
    [
        ("greek", "Πληρωμή στον λογαριασμό %s παρακαλώ."),
        ("cyrillic", "Плащане по сметка %s моля."),
        ("latin-diacritic", "Maksu tilille %s kiitos, Müller & Kovács."),
        ("maltese", "Ħlas fil-kont %s jekk jogħġbok."),
        ("mixed", "Rechnung / invoice / λογαριασμός: %s"),
    ],
)
@requires_schwifty
def test_the_validated_layer_does_not_care_what_script_surrounds_it(
    script, sentence
):
    """An IBAN, a card and an e-mail are found in Greek, Cyrillic and Maltese
    prose exactly as in German.

    This is the half of the multilingual problem that is already solved: the
    identifier is ASCII, the checksum is arithmetic, and the surrounding
    language contributes nothing. The name layer is where the twenty-four
    languages actually are.
    """
    iban = _iban_for("DE")
    assert [v for _s, _e, v in find_ibans(sentence % iban)] == [iban], script
    card = "4111111111111111"
    assert [v for _s, _e, v in find_cards(sentence % card)] == [card], script
    email = "vorname.nachname@example.eu"
    assert [v for _s, _e, v in find_emails(sentence % email)] == [email], script


def test_a_non_ascii_digit_account_number_is_a_known_gap_in_every_language():
    """Stated in `docs/limits.md` as an ASCII limit; pinned here as a
    per-language one, because "the validated layer is language-independent"
    is only true for languages written with ASCII digits."""
    arabic_indic = "٤١١١١١١١١١١١١١١١"
    assert find_cards(f"Payment {arabic_indic} please.") == []
    full_width = "４１１１１１１１１１１１１１１１"
    assert find_cards(f"Payment {full_width} please.") == []


# ---------------------------------------------------------------------------
# The class this measurement must NOT be read as clearing - now closed
# ---------------------------------------------------------------------------

#: A word character glued to the front of a grouped card number AND a line
#: break inside it. Each half was handled and the intersection was not: this
#: shape cleared the egress gate with "No PII detected" and the whole card
#: left the machine.
PREVIOUSLY_LEAKING_SHAPE = "Ref4111 1111\n1111 1111"


def test_the_glued_and_wrapped_card_is_caught_now():
    """This test was written as a PIN ON A LEAK and is now an assertion that
    the leak is closed.

    It was reported by independent verification, reproduced at the previous
    tip, and pinned green-while-leaking so that a fix would fail loudly. Main's
    identifier repair is that fix, and this is the loud failure being
    converted into a guarantee rather than deleted - the shape stays in the
    suite under its own name, because the class has been rediscovered in this
    programme more than once.
    """
    safe, _reason, categories = is_safe_for_external_llm(PREVIOUSLY_LEAKING_SHAPE)
    assert safe is False, "the glued-and-wrapped card leaks again"
    assert "credit_card" in categories, categories
    assert [value for _s, _e, value in find_cards(PREVIOUSLY_LEAKING_SHAPE)] == [
        "4111111111111111"
    ]


@pytest.mark.parametrize(
    "language, template",
    [
        ("de", "Rechnung %s Ende"),
        ("el", "Λογαριασμός %s τέλος"),
        ("bg", "Сметка %s край"),
        ("fi", "Lasku %s loppu"),
        ("hu", "Számla %s vége"),
        ("mt", "Kont %s tmiem"),
    ],
)
def test_the_closed_leak_is_closed_in_every_language(language, template):
    """The class was arithmetic and layout, so the fix has to hold in every
    language too - and the per-language name measurement says nothing about
    it either way, which is why this file carries both."""
    safe, _reason, categories = is_safe_for_external_llm(
        template % PREVIOUSLY_LEAKING_SHAPE
    )
    assert safe is False, language
    assert "credit_card" in categories, (language, categories)
