from __future__ import annotations

import os
from typing import Mapping, Optional

LEGACY_ENV: dict[str, str] = {
    "BRAIN_CREDENTIALS_MASTER_KEY": "PRIVACY_SHIELD_CREDENTIALS_MASTER_KEY",
    "BRAIN_DEVICE_CLASS": "PRIVACY_SHIELD_DEVICE_CLASS",
    "BRAIN_EMBEDDED_LOCAL_MODEL_API_KEY": "PRIVACY_SHIELD_EMBEDDED_LOCAL_MODEL_API_KEY",
    "BRAIN_EMBEDDED_LOCAL_MODEL_AVAILABLE": "PRIVACY_SHIELD_EMBEDDED_LOCAL_MODEL_AVAILABLE",
    "BRAIN_EMBEDDED_LOCAL_MODEL_COMMAND": "PRIVACY_SHIELD_EMBEDDED_LOCAL_MODEL_COMMAND",
    "BRAIN_EMBEDDED_LOCAL_MODEL_ENDPOINT": "PRIVACY_SHIELD_EMBEDDED_LOCAL_MODEL_ENDPOINT",
    "BRAIN_EMBEDDED_LOCAL_MODEL_ID": "PRIVACY_SHIELD_EMBEDDED_LOCAL_MODEL_ID",
    "BRAIN_EMBEDDED_LOCAL_MODEL_NAME": "PRIVACY_SHIELD_EMBEDDED_LOCAL_MODEL_NAME",
    "BRAIN_EMBEDDED_LOCAL_MODEL_OPENAI_COMPAT": "PRIVACY_SHIELD_EMBEDDED_LOCAL_MODEL_OPENAI_COMPAT",
    "BRAIN_ENABLE_PYMUPDF": "PRIVACY_SHIELD_ENABLE_PYMUPDF",
    "BRAIN_NATIVE_LOCAL_MODEL_API_KEY": "PRIVACY_SHIELD_NATIVE_LOCAL_MODEL_API_KEY",
    "BRAIN_NATIVE_LOCAL_MODEL_AVAILABLE": "PRIVACY_SHIELD_NATIVE_LOCAL_MODEL_AVAILABLE",
    "BRAIN_NATIVE_LOCAL_MODEL_COMMAND": "PRIVACY_SHIELD_NATIVE_LOCAL_MODEL_COMMAND",
    "BRAIN_NATIVE_LOCAL_MODEL_ENDPOINT": "PRIVACY_SHIELD_NATIVE_LOCAL_MODEL_ENDPOINT",
    "BRAIN_NATIVE_LOCAL_MODEL_ID": "PRIVACY_SHIELD_NATIVE_LOCAL_MODEL_ID",
    "BRAIN_NATIVE_LOCAL_MODEL_NAME": "PRIVACY_SHIELD_NATIVE_LOCAL_MODEL_NAME",
    "BRAIN_NATIVE_LOCAL_MODEL_OPENAI_COMPAT": "PRIVACY_SHIELD_NATIVE_LOCAL_MODEL_OPENAI_COMPAT",
    "BRAIN_PRIVACY_AUDIT_LOG": "PRIVACY_SHIELD_AUDIT_LOG",
    "BRAIN_PRIVACY_KG_DIR": "PRIVACY_SHIELD_KG_DIR",
    "BRAIN_PRIVACY_SHIELD_ONNX_AVAILABLE": "PRIVACY_SHIELD_ONNX_AVAILABLE",
    "BRAIN_PRIVACY_SHIELD_ONNX_MODE": "PRIVACY_SHIELD_ONNX_MODE",
    "BRAIN_PRIVACY_SHIELD_ONNX_MODEL_ID": "PRIVACY_SHIELD_ONNX_MODEL_ID",
    "BRAIN_PRIVACY_SHIELD_ONNX_MODEL_PATH": "PRIVACY_SHIELD_ONNX_MODEL_PATH",
    "BRAIN_PRIVACY_SHIELD_SEMANTIC_CHUNK_SIZE": "PRIVACY_SHIELD_SEMANTIC_CHUNK_SIZE",
    "BRAIN_PRIVACY_SHIELD_SEMANTIC_ENABLED": "PRIVACY_SHIELD_SEMANTIC_ENABLED",
    "BRAIN_PRIVACY_SHIELD_SEMANTIC_THRESHOLD": "PRIVACY_SHIELD_SEMANTIC_THRESHOLD",
    "BRAIN_SKILL_INTAKE_MASTER_KEY": "PRIVACY_SHIELD_SKILL_INTAKE_MASTER_KEY",
}


class LegacyEnvironmentError(RuntimeError):
    pass


def reject_legacy_env(environ: Optional[Mapping[str, str]] = None) -> None:
    env = os.environ if environ is None else environ
    found = [name for name in LEGACY_ENV if name in env]
    if found:
        renames = "; ".join(f"{name} -> {LEGACY_ENV[name]}" for name in found)
        raise LegacyEnvironmentError(
            "privacy-shield renamed its environment variables; unset the legacy name "
            f"and set its replacement: {renames}"
        )
